image: python:3.11-slim

pydocs:
    stage: deploy
    before_script:
      - pip install pydoc-markdown
    script:
      - pydoc-markdown -p saf '\{renderer: \{type: markdown, descriptive_class_title: false, render_toc: true\}\}' > saf.md
    only:
      - main