image: python:3.11-slim

pages:
    stage: deploy
    before_script:
      - pip install pydoc-markdown
      - pip install mkdocs-material
    script:
      - pydoc-markdown -I src -m pydspace.saf.relation --render-toc > Relation.md
    only:
      - main