image: python:3.11-slim

pydocs:
    stage: deploy
    before_script:
      - pip install pydoc-markdown
    script:
      - pydoc-markdown -p saf --render-toc > saf.md
      - mv saf.md doc/
    only:
      - main
    artifacts:
      name: '$CI\_JOB\_NAME'
      paths:
      - doc